# Generated by Django 5.0.6 on 2024-07-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='leaseID',
            new_name='lease',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='propertyID',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='propertyID',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='forumID',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='forummessage',
            old_name='senderID',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='unitID',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='unitID',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiverID',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='senderID',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='landlordID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rentpayment',
            old_name='leaseID',
            new_name='lease',
        ),
        migrations.RenameField(
            model_name='tenantscreening',
            old_name='tenantID',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='propertyiD',
            new_name='property',
        ),
    ]
