# Generated by Django 5.0.6 on 2024-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseApp', '0002_user_verification_code_alter_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
